---
title: "Economic Performance of Spanish Provinces in R"
author: "Aitor Alexander Gutierrez Valero"
date: '2022-08-01'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(readr)
library(dplyr)
library(ggplot2)
library(mapSpain)
```
### GDP per capita of Spanish Regions in the year 2000 and 2019
#### From the Instituto Nacional de Estadística and the Instituto Geográfico Nacional. Euros Inflation Adjusted to 2019

```{r GDPpc_Spain}
GDPpc_spain <- read_csv("GDP_Per_Capita_Spanish_Regions_2000_2019.csv") #Import Spanish Provinces Data
names(GDPpc_spain)[1]<-paste("provincia") # Change Province to provincia
census <- mapSpain::pobmun19

census["provincia"][census["provincia"] == "Araba/Álava"] <- "Álava" # Change alava
census["provincia"][census["provincia"] == "Balears, Illes"] <- "Islas Baleraes" # Change islas baleares
census["provincia"][census["provincia"] == "Rioja, La"] <- "La Rioja" #Change La Rioja

census["provincia"][census["provincia"] == "Alicante/Alacant"] <- "Alicante" #Change Alicante for both
GDPpc_spain["provincia"][GDPpc_spain["provincia"] == "Alicante/Alacant"] <- "Alicante" 

census["provincia"][census["provincia"] == "Castellón/Castelló"] <- "Castellón" #Change Castellón for both
GDPpc_spain["provincia"][GDPpc_spain["provincia"] == "Castellón/Castelló"] <- "Castellón" 

census["provincia"][census["provincia"] == "Valencia/València"] <- "Valencia" #Change Valencia for both
GDPpc_spain["provincia"][GDPpc_spain["provincia"] == "Valencia/València"] <- "Valencia" 

census_gdp <- merge(census,GDPpc_spain,by="provincia")
census_gdp["provincia"][census_gdp["provincia"] == "Palmas, Las"] <- "Las Palmas" #Change Las Palmas

codelist <- mapSpain::esp_codelist # Names and codes of all provinces, autonomous territories, and cities.

census_gdp_coded <- unique(merge(census_gdp, codelist[, c("cpro", "codauto")], all.x = TRUE))
names(census_gdp_coded)[8] <- "x2000" #Change 2000 to x2000 column name
names(census_gdp_coded)[9] <- "x2019" #Change 2019 to x2019 column name

census_gdp_province <- census_gdp_coded %>%
  distinct(provincia, .keep_all = TRUE) %>% #Choose unique instance of provincia
  select("cpro", "provincia", "x2000", "x2019", "codauto") #Keep useful columns


spain_sf <- esp_get_prov() # Province borders
spain_gdp_sf <- merge(spain_sf, census_gdp_province)

Can <- esp_get_can_box() # Box in bottom left corner of map
```


```{r Testing, echo=FALSE}
# Spain <- GENERATES A GREY MAP OF SPAIN WITH SURROUNDING COUNTRIES
# leaflet() %>%
# setView(
# lat = 39.6566,
# lng = -3.7038400,
# zoom = 5.5
# ) %>%
# addProviderEspTiles(provider = "IGNBase.Gris")
# #addProviderEspTiles(provider = "RedTransporte.Carreteras")
# Spain

# census <- mapSpain::pobmun19
# 
# # Extract CCAA from base dataset
# 
# codelist <- mapSpain::esp_codelist
# 
# census <-
#   unique(merge(census, codelist[, c("cpro", "codauto")], all.x = TRUE))
# census
# 
# # Summarize by CCAA
# census_ccaa <-
#   aggregate(cbind(pob19, men, women) ~ codauto, data = census, sum)
# 
# census_ccaa$porc_women <- census_ccaa$women / census_ccaa$pob19
# census_ccaa$porc_women_lab <-
#   paste0(round(100 * census_ccaa$porc_women, 2), "%")
# census_ccaa
# 
# # Merge into spatial data
# 
# CCAA_sf <- esp_get_ccaa()
# CCAA_sf <- merge(CCAA_sf, census_ccaa)
# Can <- esp_get_can_box()
# 
# ggplot(CCAA_sf) +
#   geom_sf(aes(fill = porc_women),
#     color = "grey70",
#     lwd = .3
#   ) +
#   geom_sf(data = Can, color = "grey70") +
#   geom_sf_label(aes(label = porc_women_lab),
#     fill = "white", alpha = 0.5,
#     size = 3,
#     label.size = 0
#   ) +
#   scale_fill_gradientn(
#     colors = hcl.colors(10, "Blues", rev = TRUE),
#     n.breaks = 10,
#     labels = function(x) {
#       sprintf("%1.1f%%", 100 * x)
#     },
#     guide = guide_legend(title = "Porc. women")
#   ) +
#   theme_void() +
#   theme(legend.position = c(0.1, 0.6))
```

```{r 2000_GDPpc}
Provinces_2000 <-
  ggplot(spain_gdp_sf) +
  geom_sf(aes(fill = x2000),
    color = "grey50",
    lwd = .05
  ) +
  geom_sf(data = Can, color = "grey40") +
  geom_sf_label(aes(label = provincia),
    fill = "white", alpha = 0,
    size = 1.2,
    label.size = 0
  ) +
  scale_fill_gradientn(
    colors = hcl.colors(10, "Cividis", rev = TRUE),
    n.breaks = 10,
    limits = c(10000, 37000),
    guide = guide_legend(title = "GDPPC / €")
  ) +
  theme_void() +
  theme(legend.position = c(0.1, 0.6)) +
  ggtitle("Economic Growth of Spanish Provinces in 2000", subtitle = "Inflation Adjusted (2019 Euros)")
Provinces_2000

#ggsave("GDPPC_2000.png", dpi = 800)
```

```{r 2019_GDPpc,}
Provinces_2019 <- 
  ggplot(spain_gdp_sf) +
  geom_sf(aes(fill = x2019),
    color = "grey50",
    lwd = .05
  ) +
  geom_sf(data = Can, color = "grey40") +
  geom_sf_label(aes(label = provincia),
    fill = "white", alpha = 0,
    size = 1.2,
    label.size = 0,
    colour = "black"
  ) +
  scale_fill_gradientn(
    colors = hcl.colors(10, "Cividis", rev = TRUE),
    n.breaks = 10,
    limits = c(10000, 37000),
    guide = guide_legend(title = "GDPPC / €")
  ) +
  theme_void() +
  theme(legend.position = c(0.1, 0.6)) +
  ggtitle("Economic Production of Spanish Provinces in 2019", subtitle = "Inflation Adjusted (2019 Euros)")
Provinces_2019

#ggsave("GDPPC_2019.png", dpi = 800)
```

```{r 2000_2019_GDPpc_Absolute_Change}
spain_gdp_sf <- spain_gdp_sf %>% #Create Absolute and Percent Columns
  mutate(Absolute = x2019-x2000,
         Percent = (x2019-x2000)/x2000*100)

Provinces_Absolute_Change <-
  ggplot(spain_gdp_sf) +
  geom_sf(aes(fill = Absolute),
    color = "grey50",
    lwd = .05
  ) +
  geom_sf(data = Can, color = "grey40") +
  geom_sf_label(aes(label = provincia),
    fill = "white", alpha = 0,
    size = 1.2,
    label.size = 0,
    colour = "black"
  ) +
  scale_fill_gradientn(
    colors = hcl.colors(10, "Cividis", rev = TRUE),
    n.breaks = 10,
    guide = guide_legend(title = "Change in GDPPC / €")
  ) +
  theme_void() +
  theme(legend.position = c(0.1, 0.6)) +
  ggtitle("Economic Growth of Spanish Provinces, 2000 to 2019", subtitle = "Inflation Adjusted (2019 Euros)")
Provinces_Absolute_Change

#ggsave("GDPPC_Absolute_Change.png", dpi = 800)
```

```{r 2000_2019_GDPpc_Percent_Change}
Provinces_Percent_Change <-
  ggplot(spain_gdp_sf) +
  geom_sf(aes(fill = Percent),
    color = "grey50",
    lwd = .05
  ) +
  geom_sf(data = Can, color = "grey40") +
  geom_sf_label(aes(label = provincia),
    fill = "white", alpha = 0,
    size = 1.2,
    label.size = 0,
    colour = "black"
  ) +
  scale_fill_gradientn(
    colors = hcl.colors(10, "Cividis", rev = TRUE),
    n.breaks = 10,
    guide = guide_legend(title = "Change in GDPPC / %")
  ) +
  theme_void() +
  theme(legend.position = c(0.1, 0.6)) +
  ggtitle("Economic Growth of Spanish Provinces, 2000 to 2019")
Provinces_Percent_Change

ggsave("GDPPC_Percent_Change.png", dpi = 800)
```

